x-common:
  python: &python
    build: .
    command: bash
    volumes:
      - ./:/home/dev/workspace
      - ./ipython_config.py:/home/dev/.ipython/profile_default/ipython_config.py
      - dev_home:/home/dev
    working_dir: /home/dev/workspace
    shm_size: '4gb'

services:
  shell:
    <<: *python
    command: bash
    profiles: [debug]

  notebook:
    <<: *python
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser
    ports:
      - 8888:8888

  lab:
    <<: *python
    command: jupyter-lab --ip 0.0.0.0 --port 9999 --no-browser
    ports:
      - 9999:9999

volumes:
  dev_home:
