# docker-compose.override.yml template to enable GPU acceleration using Nvidia CUDA
x-common:
  python: &python
    # Allow the container to use the GPU
    # https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

services:
  shell:
    <<: *python

  notebook:
    <<: *python

  lab:
    <<: *python
