x-common:
  python: &python
    build: .
    command: bash
    volumes:
      - ./:/home/dev/workspace
    working_dir: /home/dev/workspace

services:
  shell:
    <<: *python
    command: bash
    profiles: [debug]

  notebook:
    <<: *python
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser
    ports:
      - 8888:8888

  lab:
    <<: *python
    command: jupyter-lab --ip 0.0.0.0 --port 8888 --no-browser
    ports:
      - 9999:8888
