# docker-compose.override.yml template to enable GPU acceleration using Nvidia CUDA
x-common:
  python: &python
    # Install CUDA-specific dependencies
    # https://pytorch.org/get-started/locally/
    build:
      args:
        PYTORCH_INSTALL_FLAGS: pytorch-cuda=11.7 -c pytorch -c nvidia
    # Allow the container to use the GPU
    # https://docs.docker.com/compose/gpu-support/
    deploy: &gpu
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

services:
  shell:
    <<: *python

  notebook:
    <<: *python

  lab:
    <<: *python
